#服务配置
server:
  port: 8314
  max-http-header-size: 20480
  servlet:
    context-path: /Scm6Adb
    encoding:
      charset: UTF-8
#spring相关配置
spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-request-size: 20480MB
      max-file-size: 20480MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm
    locale: zh_CN
    serialization:
      # 格式化输出
      indent_output: false
#mybaits相关配置
mybatis-plus:
  mapper-locations: classpath*:com/lplb/**/mapping/*.xml, classpath:/META-INF/modeler-mybatis-mappings/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true
      logic-delete-field: delete  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略@TableLogic)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    enable-sql-runner: true
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
jasypt:
  encryptor:
    password: vh^onsYFUx^DMCKK
# 文件访问路劲
file:
  staticAccessPath: /file/**
  uploadFolder: /home/wangg/Scm6A/server/file/
  requestPath: /file/
#swagger:
#  production: false
#  basic:
#    enable: true
#    username: intestinedb
#    password: intestinedb@123
